services:
  finance-ai-platform:
    build: .
    container_name: finance-ai-platform
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    gpus: all
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

    

  data-cleaner:
    build: .
    container_name: finance-data-cleaner
    volumes:
      - .:/app
    env_file:
      - .env
    command: python src/data/clean.py --dataset all