apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-llm-api
  namespace: finance-ai
  labels:
    app.kubernetes.io/name: finance-llm-api
    app.kubernetes.io/part-of: finance-llm-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: finance-llm-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: finance-llm-api
        app.kubernetes.io/part-of: finance-llm-platform
    spec:
      serviceAccountName: finance-inference-sa
      containers:
        - name: finance-llm-api
          image: 671607590681.dkr.ecr.us-east-1.amazonaws.com/finance-llm-platform-inference:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: USE_MOCK_MODEL
              value: "true"
            - name: BASE_MODEL_NAME
              value: "Qwen/Qwen2.5-3B-Instruct"
            - name: ADAPTER_S3_URI
              value: "s3://finance-llm-local-artifacts-671607590681-us-east-1/models/qwen2.5-3b-finance/runB-r16-lr2e4/adapter/"
            - name: MODEL_ID
              value: "qwen2.5-3b-finance-runB-r16-lr2e4"
            - name: LOAD_IN_4BIT
              value: "true"
            - name: FINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: finance-api-secret
                  key: FINANCE_API_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
